# The API spec of AGIEF Persistence services in YAML
swagger: '2.0'
info:
  title: AGI Experimental Framework Persistence Service
  description: The persistence service is implements by the PostgREST program. See https://github.com/begriffs/postgrest/wiki/Routing
  version: "1.0.0"
# the domain of the service
host: agi.io
# array of all schemes that your API supports
schemes:
  - https
# will be prefixed to all paths
basePath: /v1
produces:
  - application/json
paths:
  /:
    get:
      summary: Retrieves a list of tables and views
      description: |
        The list of accessible tables and views is returned. 
      tags:
        - Meta
      responses:
        200:
          description: OK

  /{table_or_view}:
    get:
      summary: Retrieves the contents of a table or view. 
      description: |
        Returns the content of a table or view as a JSON Array of rows. Each row is a JSON Object. An arbitrary number of column arguments may be specified, where field is the name of a column in the table or view. The value of the column arguments should be an operator and a value, as defined in github.com/begriffs/postgrest/wiki/Routing
      tags:
        - Data
      parameters:
        - name: table_or_view
          in: path
          description: "Name of the table or view to query."
          required: true
          type: string
        - name: column
          in: query
          description: "Column or field to use for filtering."
          required: false
          type: string
      responses:
        200:
          description: OK

  /{table}:
    post:
      summary: Creates a new row in the specified table.
      description: |
        Appends a new row to the specified table. The body of the request should contain a JSON representation of the columns of the new row. See github.com/begriffs/postgrest/wiki/Routing
      tags:
        - Data
      parameters:
        - name: table
          in: path
          description: "Name of the table that will have an additional row."
          required: true
          type: string
      responses:
        200:
          description: OK

    patch:
      summary: Modifies rows in the specified table.
      description: |
        Modifies rows in the specified table. The body of the request should contain a JSON representation of the modified columns of the rows. Use a number of column parameters to filter the rows affected (typically reduced to 1 e.g. by using a primary key). See github.com/begriffs/postgrest/wiki/Routing
      tags:
        - Data
      parameters:
        - name: table
          in: path
          description: "Name of the table whose rows are modified."
          required: true
          type: string
        - name: column
          in: query
          description: "Column or field to use for filtering."
          required: false
          type: string
      responses:
        200:
          description: OK

    delete:
      summary: Deletes rows in the specified table.
      description: |
        Deletes rows in the specified table. Use a number of column parameters to filter the rows affected (typically reduced to 1 e.g. by using a primary key). See github.com/begriffs/postgrest/wiki/Routing
      tags:
        - Data
      parameters:
        - name: table
          in: path
          description: "Name of the table whose rows are modified."
          required: true
          type: string
        - name: column
          in: query
          description: "Column or field to use for filtering."
          required: false
          type: string
      responses:
        200:
          description: OK

