swagger: '2.0'
info:
  title: AGI Experimental Framework Persistence Service
  description: 'The persistence service is implements by the PostgREST program. See https://github.com/begriffs/postgrest/wiki/Routing'
  version: 1.0.0
host: localhost:8080
schemes:
  - http
basePath: /
produces:
  - application/json
paths:
  /:
    get:
      summary: Retrieves a list of tables and views
      description: "The list of accessible tables and views is returned. \n"
      tags:
        - Meta
      responses:
        '200':
          description: OK
  /nodes:
    get:
      summary: Retrieves the contents of a table or view.
      description: >
        Returns the content of a table or view as a JSON Array of rows. Each row
        is a JSON Object. An arbitrary number of column arguments may be
        specified, where field is the name of a column in the table or view. The
        value of the column arguments should be an operator and a value, as
        defined in github.com/begriffs/postgrest/wiki/Routing
      tags:
        - Data
      parameters:
        - name: id
          in: query
          description: id of record
          required: false
          type: integer
        - name: name
          in: query
          description: name of node
          required: false
          type: string
        - name: host
          in: query
          description: name of host
          required: false
          type: string
        - name: port
          in: query
          description: port number
          required: false
          type: integer          
      responses:
        '200':
          description: successful operation
          schema:
            type: array
            items:
              $ref: '#/definitions/nodeModel'
        '400':
          description: Invalid status value
    post:
      summary: Creates a new row in the specified table.
      description: >
        Appends a new row to the specified table. The body of the request should
        contain a JSON representation of the columns of the new row. See
        github.com/begriffs/postgrest/wiki/Routing
      tags:
        - Data
      parameters:
        - name: table
          in: path
          description: Name of the table that will have an additional row.
          required: true
          type: string
      parameters:
        - in: body
          name: body
          description: json object that describes the new row fields and values
          required: true
          schema:
            $ref: '#/definitions/nodeModel'
      responses:
        '201':
          description: Created
        '400':
          description: Bad Operation
definitions:
  nodeModel:
    type: object
    properties:
      name:
        type: string
      host:
        type: string
      port:
        type: integer        